///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CarInOutModelParkingControlList {
/*
{
  "id": 68,
  "carNo": "20우1234",
  "inoutType": "AMA002",
  "carAlias": "TEST",
  "inoutCreDt": 1523608242000
} 
*/

  int id;
  String carNo;
  String inoutType;
  String carAlias;
  int inoutCreDt;

  CarInOutModelParkingControlList({
    this.id,
    this.carNo,
    this.inoutType,
    this.carAlias,
    this.inoutCreDt,
  });
  CarInOutModelParkingControlList.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    carNo = json["carNo"]?.toString();
    inoutType = json["inoutType"]?.toString();
    carAlias = json["carAlias"]?.toString();
    inoutCreDt = json["inoutCreDt"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["carNo"] = carNo;
    data["inoutType"] = inoutType;
    data["carAlias"] = carAlias;
    data["inoutCreDt"] = inoutCreDt;
    return data;
  }
}

class CarInOutModel {
/*
{
  "totalCount": 2,
  "parkingControlList": [
    {
      "id": 68,
      "carNo": "20우1234",
      "inoutType": "AMA002",
      "carAlias": "TEST",
      "inoutCreDt": 1523608242000
    }
  ]
} 
*/

  int totalCount;
  List<CarInOutModelParkingControlList> parkingControlList;

  CarInOutModel({
    this.totalCount,
    this.parkingControlList,
  });
  CarInOutModel.fromJson(Map<String, dynamic> json) {
    totalCount = json["totalCount"]?.toInt();
  if (json["parkingControlList"] != null) {
  var v = json["parkingControlList"];
  var arr0 = List<CarInOutModelParkingControlList>();
  v.forEach((v) {
  arr0.add(CarInOutModelParkingControlList.fromJson(v));
  });
    parkingControlList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalCount"] = totalCount;
    if (parkingControlList != null) {
      var v = parkingControlList;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["parkingControlList"] = arr0;
    }
    return data;
  }
}
