///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DeliveryModelParcelList {
/*
{
  "parcelGetId": 0,
  "parcelStatusChangeDt": 0,
  "parcelStatus": "string",
  "parcelCompany": "string",
  "parcelBoxNo": "string",
  "parcelBoxDtlNo": "string",
  "confirmYn": "Y"
} 
*/

  int parcelGetId;
  int parcelStatusChangeDt;
  String parcelStatus;
  String parcelCompany;
  String parcelBoxNo;
  String parcelBoxDtlNo;
  String confirmYn;

  DeliveryModelParcelList({
    this.parcelGetId,
    this.parcelStatusChangeDt,
    this.parcelStatus,
    this.parcelCompany,
    this.parcelBoxNo,
    this.parcelBoxDtlNo,
    this.confirmYn,
  });
  DeliveryModelParcelList.fromJson(Map<String, dynamic> json) {
    parcelGetId = json["parcelGetId"]?.toInt();
    parcelStatusChangeDt = json["parcelStatusChangeDt"]?.toInt();
    parcelStatus = json["parcelStatus"]?.toString();
    parcelCompany = json["parcelCompany"]?.toString();
    parcelBoxNo = json["parcelBoxNo"]?.toString();
    parcelBoxDtlNo = json["parcelBoxDtlNo"]?.toString();
    confirmYn = json["confirmYn"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["parcelGetId"] = parcelGetId;
    data["parcelStatusChangeDt"] = parcelStatusChangeDt;
    data["parcelStatus"] = parcelStatus;
    data["parcelCompany"] = parcelCompany;
    data["parcelBoxNo"] = parcelBoxNo;
    data["parcelBoxDtlNo"] = parcelBoxDtlNo;
    data["confirmYn"] = confirmYn;
    return data;
  }
}

class DeliveryModel {
/*
{
  "totalCount": 10,
  "parcelList": [
    {
      "parcelGetId": 0,
      "parcelStatusChangeDt": 0,
      "parcelStatus": "string",
      "parcelCompany": "string",
      "parcelBoxNo": "string",
      "parcelBoxDtlNo": "string",
      "confirmYn": "Y"
    }
  ]
} 
*/

  int totalCount;
  List<DeliveryModelParcelList> parcelList;

  DeliveryModel({
    this.totalCount,
    this.parcelList,
  });
  DeliveryModel.fromJson(Map<String, dynamic> json) {
    totalCount = json["totalCount"]?.toInt();
  if (json["parcelList"] != null) {
  var v = json["parcelList"];
  var arr0 = List<DeliveryModelParcelList>();
  v.forEach((v) {
  arr0.add(DeliveryModelParcelList.fromJson(v));
  });
    parcelList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalCount"] = totalCount;
    if (parcelList != null) {
      var v = parcelList;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["parcelList"] = arr0;
    }
    return data;
  }
}
