///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EmsUsageModel {
/*
{
  "energyType": "GAS",
  "thisMonthUsage": 0,
  "lastMonthUsage": 0,
  "lastYearUsage": 0
} 
*/

  String energyType;
  double thisMonthUsage;
  double lastMonthUsage;
  double lastYearUsage;

  EmsUsageModel({
    this.energyType,
    this.thisMonthUsage,
    this.lastMonthUsage,
    this.lastYearUsage,
  });
  EmsUsageModel.fromJson(Map<String, dynamic> json) {
    energyType = json["energyType"]?.toString();
    thisMonthUsage = json["thisMonthUsage"]?.toDouble();
    lastMonthUsage = json["lastMonthUsage"]?.toDouble();
    lastYearUsage = json["lastYearUsage"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["energyType"] = energyType;
    data["thisMonthUsage"] = thisMonthUsage;
    data["lastMonthUsage"] = lastMonthUsage;
    data["lastYearUsage"] = lastYearUsage;
    return data;
  }
}





class EmsUsageReportModel {
/*
{
  "energyType": "GAS",
  "usages": [
    10
  ]
} 
*/

  String energyType;
  List<double> usages;

  EmsUsageReportModel({
    this.energyType,
    this.usages,
  });
  EmsUsageReportModel.fromJson(Map<String, dynamic> json) {
    energyType = json["energyType"]?.toString();
  if (json["usages"] != null) {
  var v = json["usages"];
  var arr0 = List<double>();
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    usages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["energyType"] = energyType;
    if (usages != null) {
      var v = usages;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["usages"] = arr0;
    }
    return data;
  }
}