///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EnergyReportModelUsageList {
/*
{
  "period": "YEAR",
  "usage": [
    10.01
  ],
  "sameAreaTypeUsage": [
    10.01
  ],
  "displayDate": [
    1534901125
  ],
  "startDate": 1534901125,
  "endDate": 1534901125,
  "energyType": "ELEC"
} 
*/

  String period;
  List<double> usage;
  List<double> sameAreaTypeUsage;
  List<int> displayDate;
  int startDate;
  int endDate;
  String energyType;

  EnergyReportModelUsageList({
    this.period,
    this.usage,
    this.sameAreaTypeUsage,
    this.displayDate,
    this.startDate,
    this.endDate,
    this.energyType,
  });
  EnergyReportModelUsageList.fromJson(Map<String, dynamic> json) {
    period = json["period"]?.toString();
  if (json["usage"] != null) {
  var v = json["usage"];
  var arr0 = List<double>();
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    usage = arr0;
    }
  if (json["sameAreaTypeUsage"] != null) {
  var v = json["sameAreaTypeUsage"];
  var arr0 = List<double>();
  v.forEach((v) {
  arr0.add(v.toDouble());
  });
    sameAreaTypeUsage = arr0;
    }
  if (json["displayDate"] != null) {
  var v = json["displayDate"];
  var arr0 = List<int>();
  v.forEach((v) {
  arr0.add(v.toInt());
  });
    displayDate = arr0;
    }
    startDate = json["startDate"]?.toInt();
    endDate = json["endDate"]?.toInt();
    energyType = json["energyType"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["period"] = period;
    if (usage != null) {
      var v = usage;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["usage"] = arr0;
    }
    if (sameAreaTypeUsage != null) {
      var v = sameAreaTypeUsage;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["sameAreaTypeUsage"] = arr0;
    }
    if (displayDate != null) {
      var v = displayDate;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data["displayDate"] = arr0;
    }
    data["startDate"] = startDate;
    data["endDate"] = endDate;
    data["energyType"] = energyType;
    return data;
  }
}

class EnergyReportModel {
/*
{
  "usageList": [
    {
      "period": "YEAR",
      "usage": [
        10.01
      ],
      "sameAreaTypeUsage": [
        10.01
      ],
      "displayDate": [
        1534901125
      ],
      "startDate": 1534901125,
      "endDate": 1534901125,
      "energyType": "ELEC"
    }
  ]
} 
*/

  List<EnergyReportModelUsageList> usageList;

  EnergyReportModel({
    this.usageList,
  });
  EnergyReportModel.fromJson(Map<String, dynamic> json) {
  if (json["usageList"] != null) {
  var v = json["usageList"];
  var arr0 = List<EnergyReportModelUsageList>();
  v.forEach((v) {
  arr0.add(EnergyReportModelUsageList.fromJson(v));
  });
    usageList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (usageList != null) {
      var v = usageList;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["usageList"] = arr0;
    }
    return data;
  }
}
