///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NoticeModelNoticeList {
/*
{
  "bbsId": 0,
  "bbsTitle": "제목",
  "bbsContent": "string",
  "bbsHits": 0,
  "bbsCreDt": 0,
  "bbsWriter": "관리자",
  "isNew": "true"
} 
*/

  int bbsId;
  String bbsTitle;
  String bbsContent;
  int bbsHits;
  int bbsCreDt;
  String bbsWriter;
  String isNew;

  NoticeModelNoticeList({
    this.bbsId,
    this.bbsTitle,
    this.bbsContent,
    this.bbsHits,
    this.bbsCreDt,
    this.bbsWriter,
    this.isNew,
  });
  NoticeModelNoticeList.fromJson(Map<String, dynamic> json) {
    bbsId = json["bbsId"]?.toInt();
    bbsTitle = json["bbsTitle"]?.toString();
    bbsContent = json["bbsContent"]?.toString();
    bbsHits = json["bbsHits"]?.toInt();
    bbsCreDt = json["bbsCreDt"]?.toInt();
    bbsWriter = json["bbsWriter"]?.toString();
    isNew = json["isNew"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["bbsId"] = bbsId;
    data["bbsTitle"] = bbsTitle;
    data["bbsContent"] = bbsContent;
    data["bbsHits"] = bbsHits;
    data["bbsCreDt"] = bbsCreDt;
    data["bbsWriter"] = bbsWriter;
    data["isNew"] = isNew;
    return data;
  }
}

class NoticeModel {
/*
{
  "totalCount": 0,
  "noticeList": [
    {
      "bbsId": 0,
      "bbsTitle": "제목",
      "bbsContent": "string",
      "bbsHits": 0,
      "bbsCreDt": 0,
      "bbsWriter": "관리자",
      "isNew": "true"
    }
  ]
} 
*/

  int totalCount;
  List<NoticeModelNoticeList> noticeList;

  NoticeModel({
    this.totalCount,
    this.noticeList,
  });
  NoticeModel.fromJson(Map<String, dynamic> json) {
    totalCount = json["totalCount"]?.toInt();
  if (json["noticeList"] != null) {
  var v = json["noticeList"];
  var arr0 = List<NoticeModelNoticeList>();
  v.forEach((v) {
  arr0.add(NoticeModelNoticeList.fromJson(v));
  });
    noticeList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalCount"] = totalCount;
    if (noticeList != null) {
      var v = noticeList;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data["noticeList"] = arr0;
    }
    return data;
  }
}
