import 'dart:convert';

import '../model/user_home_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RoutineModelDevicesTraitsCommandList {
	/*
	{
	  "command": "power",
	  "value": "on"
	} 
	*/

	String command;
	String value;

	RoutineModelDevicesTraitsCommandList({
		this.command,
		this.value,
	});
	RoutineModelDevicesTraitsCommandList.fromJson(Map < String, dynamic > json) {
		command = json["command"] ?.toString();
		value = json["value"] ?.toString();
	}
	Map < String, dynamic > toJson() {
		final Map < String, dynamic > data = Map < String, dynamic > ();
		data["command"] = command;
		data["value"] = value;
		return data;
	}
}

class RoutineModelDevicesTraits {
	/*
	{
	  "commandList": [
	    {
	      "command": "power",
	      "value": "on"
	    }
	  ]
	} 
	*/

	List < RoutineModelDevicesTraitsCommandList > commandList;

	RoutineModelDevicesTraits({
		this.commandList,
	});
	RoutineModelDevicesTraits.fromJson(Map < String, dynamic > json) {
		if (json["commandList"] != null) {
			var v = json["commandList"];
			var arr0 = List < RoutineModelDevicesTraitsCommandList > ();
			v.forEach((v) {
				arr0.add(RoutineModelDevicesTraitsCommandList.fromJson(v));
			});
			commandList = arr0;
		}
	}
	Map < String, dynamic > toJson() {
		final Map < String, dynamic > data = Map < String, dynamic > ();
		if (commandList != null) {
			var v = commandList;
			var arr0 = List();
			v.forEach((v) {
				arr0.add(v.toJson());
			});
			data["commandList"] = arr0;
		}
		return data;
	}
}

// class RoutineModelDevicesHomedevice {
// 	/*
// 	{
// 	  "id": 12,
// 	  "home_id": 122,
// 	  "device_id": "012711",
// 	  "device_model_id": 4,
// 	  "device_name": "주방",
// 	  "home_location_id": 0
// 	} 
// 	*/

// 	int id;
// 	int homeId;
// 	String deviceId;
// 	int deviceModelId;
// 	String deviceName;
// 	int homeLocationId;

// 	RoutineModelDevicesHomedevice({
// 		this.id,
// 		this.homeId,
// 		this.deviceId,
// 		this.deviceModelId,
// 		this.deviceName,
// 		this.homeLocationId,
// 	});
// 	RoutineModelDevicesHomedevice.fromJson(Map < String, dynamic > json) {
// 		id = json["id"] ?.toInt();
// 		homeId = json["home_id"] ?.toInt();
// 		deviceId = json["device_id"] ?.toString();
// 		deviceModelId = json["device_model_id"] ?.toInt();
// 		deviceName = json["device_name"] ?.toString();
// 		homeLocationId = json["home_location_id"] ?.toInt();
// 	}
// 	Map < String, dynamic > toJson() {
// 		final Map < String, dynamic > data = Map < String, dynamic > ();
// 		data["id"] = id;
// 		data["home_id"] = homeId;
// 		data["device_id"] = deviceId;
// 		data["device_model_id"] = deviceModelId;
// 		data["device_name"] = deviceName;
// 		data["home_location_id"] = homeLocationId;
// 		return data;
// 	}
// }

class RoutineModelDevices {
	/*
	{
	  "id": 0,
	  "routine_id": 0,
	  "homedevice": {
	    "id": 12,
	    "home_id": 122,
	    "device_id": "012711",
	    "device_model_id": 4,
	    "device_name": "주방",
	    "home_location_id": 0
	  },
	  "traits": {
	    "commandList": [
	      {
	        "command": "power",
	        "value": "on"
	      }
	    ]
	  }
	} 
	*/

	int id;
	int routineId;
	UserHomeDevices homedevice;
	RoutineModelDevicesTraits traits;

	RoutineModelDevices({
		this.id,
		this.routineId,
		this.homedevice,
		this.traits,
	});
	RoutineModelDevices.fromJson(Map < String, dynamic > json) {
		id = json["id"] ?.toInt();
		routineId = json["routine_id"] ?.toInt();
		homedevice = json["homedevice"] != null ? UserHomeDevices.fromJson(json["homedevice"]) : null;
		traits = json["traits"] != null ? RoutineModelDevicesTraits.fromJson(json["traits"]) : null;
	}
	Map < String, dynamic > toJson() {
		final Map < String, dynamic > data = Map < String, dynamic > ();
		data["id"] = id;
		data["routine_id"] = routineId;
		if (homedevice != null) {
			data["homedevice"] = homedevice.toJson();
		}
		if (traits != null) {
			data["traits"] = traits.toJson();
		}
		return data;
	}

	RoutineModelDevices clone() {
		final jsonResponse = json.decode(json.encode(this));
		return RoutineModelDevices.fromJson(jsonResponse as Map < String, dynamic > );
	}
}

class RoutineModel {
	/*
	{
	  "id": 0,
	  "routine_name": "외출 모드",
	  "devices": [
	    {
	      "id": 0,
	      "routine_id": 0,
	      "homedevice": {
	        "id": 12,
	        "home_id": 122,
	        "device_id": "012711",
	        "device_model_id": 4,
	        "device_name": "주방",
	        "home_location_id": 0
	      },
	      "traits": {
	        "commandList": [
	          {
	            "command": "power",
	            "value": "on"
	          }
	        ]
	      }
	    }
	  ]
	} 
	*/

	int id;
	String routineName;
	List < RoutineModelDevices > devices;

	RoutineModel({
		this.id,
		this.routineName,
		this.devices,
	});
	RoutineModel.fromJson(Map < String, dynamic > json) {
		id = json["id"] ?.toInt();
		routineName = json["routine_name"] ?.toString();
		if (json["devices"] != null) {
			var v = json["devices"];
			var arr0 = List < RoutineModelDevices > ();
			v.forEach((v) {
				arr0.add(RoutineModelDevices.fromJson(v));
			});
			devices = arr0;
		}
	}
	Map < String, dynamic > toJson() {
		final Map < String, dynamic > data = Map < String, dynamic > ();
		data["id"] = id;
		data["routine_name"] = routineName;
		if (devices != null) {
			var v = devices;
			var arr0 = List();
			v.forEach((v) {
				arr0.add(v.toJson());
			});
			data["devices"] = arr0;
		}
		return data;
	}
}
